config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  resources :articles do
    resources :comments
  end

  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "signout", to: "sessions#destroy", as: "signout"

  resources :sessions, only: [:create, :destroy]

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
  validates :title, presence: true, 
  					length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
  	#where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  	where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
  	  user.provider = auth.provider
  	  user.uid = auth.uid
  	  user.name = auth.info.name
  	  user.oauth_token = auth.credentials.token
  	  user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  	  user.save!
  	end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :clear_current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def clear_current_user
  	@current_user = nil
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

	def new
    if current_user then
      @article = Article.new
    else
      redirect_to "/auth/facebook", id: "sign_in"
    end
	end

  def edit
    @article = Article.find(params[:id])
  end

	def create
	  #render json: params[:article]
    @article = Article.new(article_params)
    

    redirect_to @article if @article.save else render "new"
    #render plain: @article.to_json
    #render plain: "article saved!"
    #redirect_to @article
	end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article  
    else 
      render "edit" 
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

  def create
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.create(comment_params)
  	redirect_to article_path(@article)
  end

  def destroy
  	article = Article.find(params[:article_id])
  	comment = article.comments.find(params[:id])
  	comment.destroy

  	redirect_to article_path(article)
  end

  private
    def comment_params
    	params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.from_omniauth(env["omniauth.auth"])
  	session[:user_id] = user.id
  	redirect_to root_path
  end

  def destroy
  	session[:user_id] = nil
  	clear_current_user
  	redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment
  end	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_account_header.html.erb
<% if current_user then %>
  <p>Hello
    <%= current_user.name %>
    - 
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  </p>
<% else %>
  <p>
    <%= link_to "Sign in to create articles", "/auth/facebook", id: "sign_in" %>
  </p>  
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  
  <% if @article.errors.any? %>
    <div id ="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  	<%= f.label :title %><br>
  	<%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/articles/edit.html.erb
<%= render "account_header" %>

<h1>Edit article</h1>

<%= render "form" %>

<%= link_to "back", :back %>

app/views/articles/index.html.erb
<%= render "account_header" %>

<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
    	<%= link_to article.title, article_path(article) %>

    	<% if current_user then %>
    	  <%= link_to "edit", edit_article_path(article) %>
    	  <%= link_to "delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>
    	<% end %>  

    </li>
  <% end %>
</ul>

<% if current_user then %>
  <p>
    <%= link_to "Create article", new_article_path %>
  </p>
<% end %>  

app/views/articles/new.html.erb
<%= render "account_header" %>

<h1>New article</h1>

<%= render "form" %>

<%= link_to :back, articles_path %>

app/views/articles/show.html.erb
<%= render "account_header" %>

<h1><%= @article.title %></h1>

<p>
  <%= @article.text %>
</p>

<% if current_user then %>
  <%= link_to "edit", edit_article_path(@article) %>
<% end %>  
<%= link_to :back, articles_path %>

<h3>Add a comment: </h3>
<%= render "comments/form" %>

<% unless @article.comments.count == 0 %>
	<h3>Comments:</h3>
  <%= render @article.comments %>
<% end %>

app/views/comments/_comment.html.erb
<% unless comment.id == nil %>
  <p>
    <strong>
      <%= comment.commenter %>
    </strong>  
    <%= comment do link_to "delete", [comment.article, comment],
  	  			  method: :delete,
  	  			  data: {confirm: "are you sure?"} end %> 
  	<br>  
    <%= comment.body %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
  	<%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>